"""Runs actual common Euler/RK kernels sequentially with the host CUDA API shim."""
from pathlib import Path
import subprocess,runpy
APP=Path(__file__).resolve().parents[1]
BODY='#include "configuration/SharedGasModel.H"\n#include <cassert>\nusing namespace chmt;\nstruct Fixture {\n ugkwp::GasModelConfiguration gas;ModelConfig model;HostState h;WallProgram program;std::string error;\n Fixture(){\n gas=ugkwp::parseGasModelProperties(R"(gasMode mixtureFrozen;species(A B);speciesThermo{\n A{model linearCp;molarMass 0.028;minTemperature 100;maxTemperature 3000;coefficients(1040 0 0);}\n B{model linearCp;molarMass 0.032;minTemperature 100;maxTemperature 3000;coefficients(1040 0 0);}}diffusion{model none;})");\n assert(bindSharedGasModel(gas,model,error));model.physics.gasConductivity=1;\n model.physics.minDt=1e-12;model.physics.maxDt=.001;model.physics.cfl=.4;\n h.gas.resize(1);h.gas[0].mass=1;h.gas[0].species[0]=1;h.gas[0].energy=1e6;h.solid.resize(1);h.solid[0].condensed[0]=1;\n auto&m=h.gasMesh;m.volumes={1};m.cellCentres={{0,0,0}};m.owner={0,0};m.neighbour={-1,-1};m.periodicPartner={-1,-1};m.cellFaceOffsets={0,2};m.cellFaces={0,1};\n m.faceCentres={{-1,0,0},{1,0,0}};m.areaVectors={{-1,0,0},{1,0,0}};m.boundaryKind={BoundaryKind::Interface,BoundaryKind::Slip};m.boundaryPrimitive.resize(2);\n h.solidMesh.volumes={1};h.solidMesh.owner={0};h.solidMesh.neighbour={-1};\n h.surface.area={1};h.surface.gasFace={0};h.surface.solidFace={0};h.surface.solidCell={0};h.surface.persistentId={7};h.surface.normal={{1,0,0}};h.surface.gasDistance={1};h.surface.solidDistance={1};\n program.interval.end=.01;program.surface=h.surface;WallKnot a,z;a.time=0;z.time=.01;\n WallFaceSample sample;sample.temperature=900;sample.primaryKind=ExchangeKind::GasSolid;a.faces={sample};z.faces={sample};program.knots={a,z};\n }\n};\n\n\n#include <cstdio>\nint main(){for(int rk:{1,2,3}){\n Fixture f;f.model.physics.gasViscosity=.05;\n f.h.gas[0].momentum={0,10,0};f.h.gas[0].energy=(f.model.physics.species[0].cp0-f.model.physics.species[0].R)*600+50;\n f.h.gasMesh.thermalBoundary={ThermalBoundaryKind::FixedValue,ThermalBoundaryKind::ZeroGradient};f.h.gasMesh.boundaryPrimitive[0].temperature=300;\n for(auto& knot:f.program.knots)knot.faces[0].temperature=300;\n GasExecutionOptions options;options.timeIntegrator=rk;\n std::unique_ptr<Backend,void(*)(Backend*)> b(createBackend(f.model,f.gas,{},options,f.h,f.error),destroyBackend);assert(b);\n assert(beginGasWindow(*b,f.program,f.error));GasMicroReport report;\n if(!advanceGasMicrostep(*b,1e-4,report,f.error)){std::fprintf(stderr,"%s\\n",f.error.c_str());return 1;}\n const auto& r=b->history.records()[0];\n assert(std::abs(r.gasGradient[0].temperature.x-(r.gasTrace[0].temperature-300))<1e-9);\n assert(std::abs(r.gasGradient[0].velocity[1].x-r.gasTrace[0].velocity.y)<1e-10);\n assert(std::abs(r.gasTraction[0].y-.05*r.gasTrace[0].velocity.y)<1e-10);\n}}\n'
def test_record_keeps_a_coherent_gas_stage(tmp_path):
    helpers=runpy.run_path(str(APP/'tests/test_shared_backend_compile.py'))
    source=helpers['prepare_backend'](tmp_path)
    source.write_text(source.read_text()+BODY)
    exe=tmp_path/'trace'
    subprocess.run(helpers['compiler_flags'](tmp_path)+[str(source),str(APP/'mesh/Geometry.C'),'-o',str(exe)],check=True)
    subprocess.run([str(exe)],check=True)
