#include "coupling/IntervalContracts.H"
#include <cmath>
#include <iostream>
#include <stdexcept>
using namespace chmt;
static void require(bool b,const char* message){if(!b)throw std::runtime_error(message);}
static ExchangePacket packet(Real mass,Real energy,std::uint64_t face=4){ExchangePacket p;p.stage=1;p.step=1;p.geometry=2;p.face=face;p.kind=ExchangeKind::GasSolid;p.gasCell=0;p.solidCell=0;p.mass=mass;p.species[0]=mass;p.condensed[0]=mass;p.energy=p.conductive=energy;p.consumerMask=ConsumeGas;return p;}
static GasIntervalRecord record(Real a,Real b,std::uint64_t n,Real mass,Real energy){GasIntervalRecord r;r.begin=a;r.end=b;r.microSequence=n;r.gasGeometry=2;r.solidGeometry=2;r.packets.push_back(packet(mass,energy));r.packets.back().step=n;return r;}
static_assert(noexcept(std::declval<MaterialDonorReserve&>().commitPrepared(std::declval<MaterialDonorReserve::Transaction&&>())),"post-history donor publication must not throw");
int main(){try{
 std::string e; IntervalHistory h; CouplingInterval w;w.identity.sequence=1;w.begin=0;w.end=1;
 require(h.begin(w,e),"begin"); auto r=record(0,.3,1,.1,7);require(h.appendAccepted(r,e),"append first");
 require(!h.appendAccepted(r,e),"duplicate record accepted"); require(h.records().size()==1,"failed append mutated history");
 auto predictor=record(.3,1,2,.2,11);predictor.packets[0].stage=0;require(!h.appendAccepted(predictor,e),"predictor accumulated");
 auto second=record(.3,1,2,.2,11);require(h.appendAccepted(second,e),"append second");require(h.complete(),"complete history");
 auto cursor=h.cursor(); std::vector<ExchangePacket> out;std::vector<Real> radiation;Real energy=0,mass=0;
 for(Real t:{.07,.2,.3,.71,1.}){require(cursor.takeThrough(t,out,radiation,e),"overlap slice");for(auto p:out){mass+=p.mass;energy+=p.energy;}}
 require(std::abs(mass-.3)<1e-16&&energy==18,"overlap lost transfer");require(cursor.complete(),"cursor incomplete");
 require(!cursor.takeThrough(1,out,radiation,e),"zero slice accepted");
 std::vector<SolidQ> solid(1);solid[0].condensed[0]=.15;std::vector<FilmQ> film;MaterialDonorReserve reserve;
 require(reserve.reset(solid,film,0,e),"reserve reset");require(reserve.apply(r,e),"reserve first");
 auto over=record(.3,.6,2,.1,0);require(!reserve.apply(over,e),"macro donor overspent");require(std::abs(reserve.solid()[0].condensed[0]-.05)<1e-16,"failed reserve mutated");
 CouplingControls controls;controls.interval=1;controls.minimumInterval=.01;controls.gasMaxDt=.001;
 CouplingWindowController control;require(control.begin(0,2,1,controls,e),"controller begin");require(control.interval().end==1,"gas dt constrained macro H");
 WindowAssessment assessment;assessment.predictionError=100;require(control.assess(assessment)==WindowDecision::Accept,"optional accuracy forced replay");
 assessment.geometryMatches=false;require(control.assess(assessment)==WindowDecision::Replay,"geometry mismatch accepted");
 require(control.replay(e),"replay");require(control.interval().identity.epoch==1,"epoch unchanged");
 require(control.shorten(.4,e),"shorten");require(control.interval().end==.4,"shorten endpoint");
 IntervalHistory masks;require(masks.begin(w,e),"mask history begin");auto unapplied=r;unapplied.packets[0].consumerMask=0;require(!masks.appendAccepted(unapplied,e),"unapplied packet accepted");
 IntervalHistory radiated;require(radiated.begin(w,e),"radiation history begin");auto ra=r;ra.radiationEnergy={2};ra.radiationReceiver={ConsumeSolid};require(radiated.appendAccepted(ra,e),"radiation first");auto rb=second;rb.radiationEnergy={3};rb.radiationReceiver={ConsumeFilm};require(!radiated.appendAccepted(rb,e),"radiation receiver event collapsed");
 std::vector<SolidQ> emptyPore(1);MaterialDonorReserve generated;require(generated.reset(emptyPore,film,0,e),"generated reserve reset");
 MaterialDonorPlan plan;plan.interval=w;MaterialReserveKnot k0,k1;k0.time=0;k1.time=1;k0.cumulativeSolid.resize(1);k1.cumulativeSolid.resize(1);k1.cumulativeSolid[0].pore[0]=1;plan.knots={k0,k1};require(generated.setPlan(plan,e),"set production plan");
 auto produced=record(0,.5,1,0,0);auto& pp=produced.packets[0];pp.kind=ExchangeKind::PoreGas;pp.mass=.4;pp.species[0]=pp.pore[0]=.4;require(generated.apply(produced,e),"valid generated donor denied");require(std::abs(generated.solid()[0].pore[0]-.1)<1e-15,"generated donor balance");
 MaterialDonorReserve delayed;require(delayed.reset(emptyPore,film,0,e),"delayed reset");MaterialReserveKnot km=k0;km.time=.75;plan.knots={k0,km,k1};require(delayed.setPlan(plan,e),"delayed plan");require(!delayed.apply(produced,e),"future production borrowed");
 MaterialDonorReserve twoFaces;std::vector<SolidQ> one(1);one[0].condensed[0]=.15;require(twoFaces.reset(one,film,0,e),"two face reset");auto batch=record(0,.2,1,.1,0);batch.packets.push_back(packet(.1,0,5));require(!twoFaces.apply(batch,e),"incident faces spent donor twice");require(twoFaces.solid()[0].condensed[0]==.15,"aggregate failure mutated reserve");
 MaterialDonorReserve reverse;one[0].condensed[0]=0;require(reverse.reset(one,film,0,e),"reverse reset");auto paired=record(0,.2,1,-.1,0);paired.packets.push_back(packet(.1,0,5));require(!reverse.apply(paired,e),"same-step incoming credit funded outgoing donor");
 MaterialDonorReserve counter;std::vector<SolidQ> pore(1);pore[0].pore[0]=.05;require(counter.reset(pore,film,0,e),"counter reset");auto counterflow=produced;counterflow.packets[0].mass=counterflow.packets[0].pore[0]=counterflow.packets[0].species[0]=0;counterflow.packets[0].poreSweep[0]=.1;require(!counter.apply(counterflow,e),"net pore flux hid gross depletion");
 IntervalHistory trace;require(trace.begin(w,e),"gradient history begin");auto tr=r;tr.gasTrace.resize(1);tr.gasGradient.resize(1);tr.gasGradient[0].temperature.x=std::numeric_limits<Real>::infinity();require(!trace.appendAccepted(tr,e),"nonfinite gradient accepted");
 IntervalHistory stale;require(stale.begin(w,e),"stale history begin");auto wrong=r;wrong.packets[0].step=999;require(!stale.appendAccepted(wrong,e),"stale packet microstep accepted");
 MaterialDonorReserve thirds;one[0].condensed[0]=.3;require(thirds.reset(one,film,0,e),"thirds reset");
 for(int i=0;i<3;++i){auto third=record(i/3.,(i+1)/3.,i+1,.1,0);require(thirds.apply(third,e),"roundoff rejected exact donor exhaustion");}
 require(thirds.roundoff().admittedChecks>0&&thirds.roundoff().maximumDeficit>0,"donor roundoff deficit was hidden");
 auto excess=record(1,2,4,1e-12,0);require(!thirds.apply(excess,e),"physical excess hidden by donor roundoff bound");
 std::vector<Real> chunks;long double exactTotal=0;for(int i=0;i<257;++i){const Real amount=(1+i%7)*1e-5;chunks.push_back(amount);exactTotal+=amount;}
 std::vector<SolidQ> bulk(1);bulk[0].pore[0]=static_cast<Real>(exactTotal);std::vector<FilmQ> wet(1);wet[0].mass=wet[0].species[0]=static_cast<Real>(exactTotal);MaterialDonorReserve longHistory;require(longHistory.reset(bulk,wet,0,e),"long history reset");
 for(std::size_t i=0;i<chunks.size();++i){auto rvar=record(Real(i)/chunks.size(),Real(i+1)/chunks.size(),i+1,0,0);auto& porePacket=rvar.packets[0];porePacket.kind=ExchangeKind::PoreGas;porePacket.mass=porePacket.species[0]=porePacket.pore[0]=chunks[i];auto fp=porePacket;fp.kind=ExchangeKind::GasFilm;fp.solidCell=-1;fp.filmFace=0;fp.pore[0]=0;rvar.packets.push_back(fp);require(longHistory.apply(rvar,e),"variable-step pore/film donor exhaustion");}
 require(std::abs(longHistory.solid()[0].pore[0])<1e-17&&std::abs(longHistory.film()[0].mass)<1e-17,"compensated donor remainder grew with microsteps");
 MaterialDonorReserve plannedThirds;require(plannedThirds.reset(emptyPore,film,0,e),"planned thirds reset");plan.knots={k0,k1};plan.knots.back().cumulativeSolid[0].pore[0]=.3;require(plannedThirds.setPlan(plan,e),"planned thirds plan");
 for(int i=0;i<3;++i){auto planned=record(i/3.,(i+1)/3.,i+1,0,0);auto& q=planned.packets[0];q.kind=ExchangeKind::PoreGas;q.mass=q.species[0]=q.pore[0]=.1;require(plannedThirds.apply(planned,e),"planned prefix roundoff depletion");}
 MaterialDonorReserve smallSparse,largeSparse;std::vector<SolidQ> tiny(1),large(4096);tiny[0].condensed[0]=large[0].condensed[0]=1;
 require(smallSparse.reset(tiny,film,0,e)&&largeSparse.reset(large,film,0,e),"sparse reset");auto touch=record(0,.3,1,.1,0);require(smallSparse.apply(touch,e)&&largeSparse.apply(touch,e),"sparse apply");
 require(smallSparse.work().lastComponents==largeSparse.work().lastComponents&&smallSparse.work().lastOwners==largeSparse.work().lastOwners,"untouched bulk cells increased reserve apply work");
 require(smallSparse.reset(tiny,film,0,e)&&largeSparse.reset(large,film,0,e),"planned sparse reset");MaterialDonorPlan smallPlan,largePlan;smallPlan.interval=largePlan.interval=w;MaterialReserveKnot small0,small1,large0,large1;small0.time=large0.time=0;small1.time=large1.time=1;small0.cumulativeSolid.resize(1);small1.cumulativeSolid.resize(1);large0.cumulativeSolid.resize(4096);large1.cumulativeSolid.resize(4096);small1.cumulativeSolid[0].pore[0]=large1.cumulativeSolid[0].pore[0]=1;smallPlan.knots={small0,small1};largePlan.knots={large0,large1};
 require(smallSparse.setPlan(smallPlan,e)&&largeSparse.setPlan(largePlan,e),"planned sparse set");require(smallSparse.apply(touch,e)&&largeSparse.apply(touch,e),"planned sparse apply");require(smallSparse.work().lastComponents==largeSparse.work().lastComponents&&smallSparse.work().lastPlanSamples==largeSparse.work().lastPlanSamples,"untouched bulk cells increased plan sampling work");
 MaterialDonorReserve lazy;require(lazy.reset(emptyPore,film,0,e)&&lazy.setPlan(smallPlan,e),"lazy production setup");auto firstTouch=record(0,.2,1,0,0);firstTouch.packets[0].kind=ExchangeKind::PoreGas;firstTouch.packets[0].mass=firstTouch.packets[0].species[0]=firstTouch.packets[0].pore[0]=.1;require(lazy.apply(firstTouch,e),"lazy first touch");auto gap=record(.2,.8,2,0,0);gap.packets.clear();require(lazy.apply(gap,e)&&lazy.work().lastComponents==0,"unaffected owner was visited in gap");auto lastTouch=firstTouch;lastTouch.begin=.8;lastTouch.end=1;lastTouch.microSequence=lastTouch.packets[0].step=3;lastTouch.packets[0].mass=lastTouch.packets[0].species[0]=lastTouch.packets[0].pore[0]=.8;require(lazy.apply(lastTouch,e)&&std::abs(lazy.solid()[0].pore[0]-.1)<1e-15,"lazy plan lost skipped production");
 MaterialDonorReserve staged;require(staged.reset(tiny,film,0,e),"staged reserve reset");MaterialDonorReserve::Transaction transaction;require(staged.prepare(touch,transaction,e),"sparse reservation prepare");require(staged.time()==0&&staged.solid()[0].condensed[0]==1,"prepare changed actual reserve");require(transaction.componentCount()==Nc+Ns,"transaction contains unrelated material components");require(staged.commit(std::move(transaction),e),"sparse reservation commit");require(staged.time()==.3&&std::abs(staged.solid()[0].condensed[0]-.9)<1e-15,"sparse commit incorrect");require(!staged.commit(std::move(transaction),e),"reservation committed twice");
 MaterialDonorPlan excursion;excursion.interval.begin=0;excursion.interval.end=3;for(int i=0;i<4;++i){MaterialReserveKnot knot;knot.time=i;knot.cumulativeSolid.resize(1);knot.cumulativeSolid[0].condensed[0]=i==1?-2:0;excursion.knots.push_back(knot);}
 MaterialDonorReserve skipped;require(skipped.reset(tiny,film,0,e)&&skipped.setPlan(excursion,e),"excursion setup");auto emptySpan=record(0,2,1,0,0);emptySpan.packets.clear();require(skipped.apply(emptySpan,e),"empty excursion span");auto debit=record(2,3,2,.5,0);require(!skipped.apply(debit,e),"lazy sampling skipped earlier negative plan prefix");
 MaterialDonorReserve incomingLate;require(incomingLate.reset(tiny,film,0,e)&&incomingLate.setPlan(excursion,e)&&incomingLate.apply(emptySpan,e),"late incoming setup");auto credit=record(2,3,2,-1,0);require(!incomingLate.apply(credit,e),"late incoming transfer repaired earlier negative prefix");
 MaterialDonorReserve funded;require(funded.reset(tiny,film,0,e)&&funded.setPlan(excursion,e),"funded excursion setup");auto earlierCredit=record(0,.5,1,-1,0);require(funded.apply(earlierCredit,e),"earlier incoming credit");auto fundedGap=emptySpan;fundedGap.begin=.5;fundedGap.microSequence=2;require(funded.apply(fundedGap,e),"funded gap");debit.microSequence=debit.packets[0].step=3;require(funded.apply(debit,e),"valid past inflow lost during deferred prefix check");
 MaterialDonorReserve neverRetouched;require(neverRetouched.reset(tiny,film,0,e)&&neverRetouched.setPlan(excursion,e),"never touched setup");auto wholeEmpty=emptySpan;wholeEmpty.end=3;require(neverRetouched.apply(wholeEmpty,e),"never touched empty record");require(!neverRetouched.validatePlanPrefix(e),"macro final check skipped never-touched negative prefix");
 MaterialDonorPlan positiveDelayed=excursion;for(std::size_t i=0;i<positiveDelayed.knots.size();++i)positiveDelayed.knots[i].cumulativeSolid[0].condensed[0]=i<2?0:1;
 std::vector<SolidQ> zeroSolid(1);MaterialDonorReserve safeDelayed;require(safeDelayed.reset(zeroSolid,film,0,e)&&safeDelayed.setPlan(positiveDelayed,e)&&safeDelayed.apply(emptySpan,e),"positive delayed production setup");debit.microSequence=debit.packets[0].step=2;require(safeDelayed.apply(debit,e)&&safeDelayed.validatePlanPrefix(e),"valid delayed production rejected");
 std::cout<<"interval contracts: PASS\n";return 0;
 }catch(const std::exception& x){std::cerr<<x.what()<<'\n';return 1;}}
